create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  recipient_name text not null,
  intro_text_1 text not null,
  intro_text_2 text not null,
  intro_text_3 text not null,
  playlist_title text not null,
  playlist_subtitle text not null,
  surprise_title text not null,
  surprise_subtitle text not null,
  surprise_text text not null,
  unlock_code text not null default '',
  audio_url text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.guestbook_form (
  id integer primary key default 1 check (id = 1),
  title text not null,
  description text not null,
  author_label text not null,
  author_placeholder text not null,
  word_label text not null,
  word_placeholder text not null,
  message_label text not null,
  message_placeholder text not null,
  submit_text text not null,
  submitting_text text not null,
  success_title text not null,
  success_message text not null,
  write_another_text text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.capsule_cards (
  id bigint generated by default as identity primary key,
  position integer not null,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_photos (
  id bigint generated by default as identity primary key,
  position integer not null,
  url text not null,
  caption text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.letter_parts (
  id bigint generated by default as identity primary key,
  position integer not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  position integer not null,
  text text not null,
  author text not null,
  word text,
  created_at timestamptz not null default now()
);

create table if not exists public.default_words (
  id bigint generated by default as identity primary key,
  position integer not null,
  word text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.transition_messages (
  id bigint generated by default as identity primary key,
  position integer not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  author text not null,
  word text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'gallery-images',
  'gallery-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.site_settings enable row level security;
alter table public.guestbook_form enable row level security;
alter table public.capsule_cards enable row level security;
alter table public.gallery_photos enable row level security;
alter table public.letter_parts enable row level security;
alter table public.friend_messages enable row level security;
alter table public.default_words enable row level security;
alter table public.transition_messages enable row level security;
alter table public.messages enable row level security;

insert into public.site_settings (
  id,
  recipient_name,
  intro_text_1,
  intro_text_2,
  intro_text_3,
  playlist_title,
  playlist_subtitle,
  surprise_title,
  surprise_subtitle,
  surprise_text,
  unlock_code,
  audio_url
) values (
  1,
  'Toi',
  'Ce site existe pour une seule personne : ',
  'Aujourd''hui, je ne voulais pas juste t''envoyer un message. Je voulais te creer un petit endroit a toi.',
  'A l''interieur, il y a des souvenirs, des mots, des sourires, et une surprise.',
  'L''Air de la Mer',
  '02:45 / 04:12',
  E'Ton vrai cadeau \n t attend.',
  'Regarde bien dans l''enveloppe... ou autour de toi.',
  'Ce n''est pas le cadeau le plus cher, mais c''est surement l''un des plus sinceres que j''ai faits. Ce site restera ici, accessible quand tu voudras te rappeler que tu comptes.',
  '',
  'https://www.youtube.com/watch?v=y7e-GC6oGIZ'
) on conflict (id) do update set
  recipient_name = excluded.recipient_name,
  intro_text_1 = excluded.intro_text_1,
  intro_text_2 = excluded.intro_text_2,
  intro_text_3 = excluded.intro_text_3,
  playlist_title = excluded.playlist_title,
  playlist_subtitle = excluded.playlist_subtitle,
  surprise_title = excluded.surprise_title,
  surprise_subtitle = excluded.surprise_subtitle,
  surprise_text = excluded.surprise_text,
  unlock_code = excluded.unlock_code,
  audio_url = excluded.audio_url,
  updated_at = now();

insert into public.guestbook_form (
  id,
  title,
  description,
  author_label,
  author_placeholder,
  word_label,
  word_placeholder,
  message_label,
  message_placeholder,
  submit_text,
  submitting_text,
  success_title,
  success_message,
  write_another_text
) values (
  1,
  'Un mot pour {name}',
  'Nous preparons une surprise interactive pour {name}. Ecrivez un souvenir, un voeu ou un petit mot qui apparaitra sur son mur d''anniversaire !',
  'Votre Prenom / Nom',
  'Ex: Marine, Ton frere, Un ami d''enfance...',
  'Un mot qui decrit {name}',
  'Ex: Lumineuse, Solaire, Unique, Genereux...',
  'Votre Message',
  'Votre message chaleureux...',
  'Accrocher au mur',
  'Envoi en cours...',
  'Message envoye !',
  'Votre mot doux a bien ete envoye et accroche sur le mur de {name}. Merci pour votre participation !',
  'Ecrire un autre message'
) on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  author_label = excluded.author_label,
  author_placeholder = excluded.author_placeholder,
  word_label = excluded.word_label,
  word_placeholder = excluded.word_placeholder,
  message_label = excluded.message_label,
  message_placeholder = excluded.message_placeholder,
  submit_text = excluded.submit_text,
  submitting_text = excluded.submitting_text,
  success_title = excluded.success_title,
  success_message = excluded.success_message,
  write_another_text = excluded.write_another_text,
  updated_at = now();

delete from public.capsule_cards;
insert into public.capsule_cards (position, title, content) values
  (0, 'Ce que j''aime chez toi', 'Ta capacite a rendre n''importe quel moment banal en quelque chose de special et chaleureux.'),
  (1, 'Un souvenir grave', 'Ce jour-la ou l''on a ri pour absolument rien. Je m''en souviens comme si c''etait hier.'),
  (2, 'Ta qualite cachee', 'Ton ecoute silencieuse. Tu as cette maniere unique de rassurer sans meme avoir besoin de parler.'),
  (3, 'Ce que tu merites', 'De te voir avec les memes yeux que ceux avec lesquels je te regarde. Tu es exceptionnel(le).'),
  (4, 'Une phrase pour toi', '"Ne change jamais ta facon de briller, meme quand tu doutes de ta propre lumiere."');

delete from public.gallery_photos;
insert into public.gallery_photos (position, url, caption) values
  (0, 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93', 'Ce jour-la, je crois qu''on ne savait meme pas que ca allait devenir un si beau souvenir.'),
  (1, 'https://images.unsplash.com/photo-1502444330042-d1a1ddf9d779', 'Une image simple, mais un moment qui compte tellement pour moi.'),
  (2, 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59', 'Chaque detail de cette journee a sa propre histoire.');

delete from public.letter_parts;
insert into public.letter_parts (position, text) values
  (0, 'Je voulais que ce cadeau soit different.'),
  (1, 'Pas forcement grand, pas forcement cher. Mais personnel.'),
  (2, 'Quelque chose qui montre que j''ai pris le temps de penser a toi, a ce que tu representes, et a la maniere dont tu merites d''etre celebre(e).'),
  (3, 'Il y a des gens qui traversent la vie sans faire de bruit, et il y a toi.'),
  (4, 'Tu as cette lumiere qui fait du bien, cette presence qui rassure.'),
  (5, 'Cette annee, je te souhaite de realiser a quel point tu es important(e) pour ceux qui t''entourent.'),
  (6, 'N''oublie jamais que tu merites ce qu''il y a de plus beau.');

delete from public.friend_messages;
insert into public.friend_messages (position, text, author, word) values
  (0, 'Joyeux anniversaire ! Reste cette personne extraordinaire que tu es.', 'Un ami', 'Extraordinaire'),
  (1, 'Tu merites tout le bonheur du monde. Profite de ta journee !', 'Un proche', 'Unique'),
  (2, 'Une annee de plus pour briller, grandir et inspirer tout le monde autour de toi.', 'Quelqu''un qui tient a toi', 'Inspirante'),
  (3, 'Rien ne me fait plus plaisir que de te voir sourire aujourd hui.', 'Un(e) confident(e)', 'Solaire');

delete from public.default_words;
insert into public.default_words (position, word) values
  (0, 'Solaire'),
  (1, 'Unique'),
  (2, 'Bienveillante'),
  (3, 'Lumineuse'),
  (4, 'Sincere'),
  (5, 'Drole'),
  (6, 'Genereuse'),
  (7, 'Brillante'),
  (8, 'Attentionnee'),
  (9, 'Douce'),
  (10, 'Inestimable'),
  (11, 'Magique'),
  (12, 'Inspirante'),
  (13, 'Rayonnante'),
  (14, 'Precieuse'),
  (15, 'Complice'),
  (16, 'Formidable'),
  (17, 'Extraordinaire'),
  (18, 'Chaleureuse'),
  (19, 'Fidele'),
  (20, 'Souriante'),
  (21, 'Optimiste'),
  (22, 'Sensible'),
  (23, 'Creative'),
  (24, 'Adorable');

delete from public.transition_messages;
insert into public.transition_messages (position, text) values
  (0, 'Le chapitre suivant s''ouvre...'),
  (1, 'Un moment se dessine...'),
  (2, 'Souffle doux avant la suite...'),
  (3, 'L''aventure continue...'),
  (4, 'Prepare ton coeur...'),
  (5, 'La magie se prepare...');

create index if not exists capsule_cards_position_idx on public.capsule_cards (position);
create index if not exists gallery_photos_position_idx on public.gallery_photos (position);
create index if not exists letter_parts_position_idx on public.letter_parts (position);
create index if not exists friend_messages_position_idx on public.friend_messages (position);
create index if not exists default_words_position_idx on public.default_words (position);
create index if not exists transition_messages_position_idx on public.transition_messages (position);
create index if not exists messages_created_at_idx on public.messages (created_at);

-- L'application utilise SUPABASE_SERVICE_ROLE_KEY cote serveur.
-- Aucune policy publique n'est necessaire pour le navigateur.
